- name: Push to ECR
  become: true
  become_user: "{{ aws_ecr_push_user }}"
  ecr_push:
    region: "{{ aws_ecr_push_region }}"
    image: "{{ aws_ecr_push_image }}"
    tag: "{{ aws_ecr_push_tag }}"
  register: aws_ecr_push_result

- name: Save image repo
  set_fact:
    aws_ecr_push_repos: "{{ aws_ecr_push_repos|default({}).update(aws_ecr_push_result.repos)}}"
