- job:
    name: test-pip-and-virtualenv
    parent: gm-base
    run: playbooks/test-pip-and-virtualenv.yaml

- job:
    name: with-ecr-credentials
    parent: gm-base
    pre-run: playbooks/pre-aws-ecr-credentials.yaml
    secrets:
      - aws_ecr_credentials

- project:
    check:
      jobs:
        - test-pip-and-virtualenv
    gate:
      jobs:
        - test-pip-and-virtualenv
