- job:
    name: test-pip-and-virtualenv
    parent: gm-base
    run: playbooks/test-pip-and-virtualenv.yaml

- project:
    check:
      jobs:
        - test-pip-and-virtualenv
        - test-git-crypt
    gate:
      jobs:
        - test-pip-and-virtualenv
        - test-git-crypt
        - test-aws-ecr
